import: definition.yaml

concurrency:
  task:
    dbbench-std: 5
    # os-std: 5
    # alfworld-std: 5
    # cg-std: 5
    # ltp-std: 5
    # kg-std: 5
  agent:
    gpt-3.5-turbo-0613: 5
    llama-2-7b-chat: 5
    llama-2-7b-chat-tot: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      # - gpt-3.5-turbo-0613
      # - llama-2-7b-chat
      - llama-2-7b-chat-tot
    task:
      - dbbench-std
      # - os-std
      # - alfworld-std
      # - cg-std
      # - ltp-std
      # - kg-std

output: "outputs/{TIMESTAMP}"
